---
title: "2021-07-01-Sol_LeWitt"
author: "Kristen A, kkakey"
date: "7/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Sol LeWitt's Color Bands (2000)

[Original art](https://www.sollewittprints.org/artwork/lewitt-raisonne-2000-07/)

This code attempts to replicate Color Bands, Plate #08

```{r}
library(tidyverse)
library(ggforce)
library(cowplot)
```

color codes
# Yellow - "#FBF652"
# Orange - "#EE9842"
# Purple - "#7649AE"
# Red - "#DF382D"
# Green -"#60B94E"
# Blue - "#5FA2DF"

```{r}
# bottom right panel
y <- seq(from=1.3,to=0, by=-.04)
x <- rep(0,length(y))
col <- c("#5FA2DF", "#7649AE", "#EE9842", "#60B94E", 
        "#DF382D", "#7649AE",  "#FBF652", "#5FA2DF", "#EE9842",
        "#60B94E", "#DF382D", "#FBF652", "#7649AE", "#60B94E", 
        "#5FA2DF",  "#7649AE","#EE9842", "#DF382D", "#7649AE",
        "#FBF652", "#5FA2DF",  "#EE9842","#60B94E", "#DF382D", 
        "#5FA2DF","#FBF652", "#EE9842", "#7649AE", "#DF382D", 
         "#5FA2DF", "#FBF652", "#60B94E", "#EE9842")

ggplot() +
  geom_circle(aes(x0 = x, y0 = x, r = y, color=rev(col)), size=3.6) +
  theme_void() +
  theme(legend.position = "none") +
  coord_fixed(expand = T) +
  scale_color_identity() +
  ggsave("plot1.png")
```

```{r}
# left panel
col2 <- c("#EE9842", "#DF382D", "#60B94E", "#5FA2DF", "#FBF652",
     "#DF382D", "#60B94E","#7649AE", "#EE9842", "#60B94E","#DF382D",
     "#5FA2DF", "#7649AE", "#60B94E", "#5FA2DF", "#DF382D","#EE9842", 
     "#7649AE", "#FBF652", "#DF382D", "#60B94E","#EE9842", "#5FA2DF",
     "#7649AE","#60B94E","#7649AE", "#FBF652","#5FA2DF", "#EE9842", 
     "#DF382D", "#60B94E","#7649AE", "#5FA2DF", "#FBF652","#7649AE", 
     "#60B94E", "#EE9842", "#DF382D", "#5FA2DF", "#7649AE",
     "#5FA2DF","#FBF652", "#60B94E", "#EE9842", "#5FA2DF", "#DF382D")
y2 <- seq(from=(length(col2)-1)*.04,to=0, by=-.04)

ggplot() +
  geom_segment(aes(x = 0, xend=2, y = y2,yend = y2 , color=rev(col2)), size=4.3) +
  theme_void() +
  theme(legend.position = "none") +
  coord_fixed(expand = T) +
  scale_color_identity() +
  ggsave("plot2.png")
```

```{r}
# top right panel
col3 <- c("#FBF652", "#EE9842", "#7649AE", "#DF382D", "#60B94E", "#5FA2DF", 
          "#FBF652", "#5FA2DF", "#60B94E", "#7649AE", "#DF382D", "#5FA2DF",
          "#FBF652", "#60B94E", "#DF382D", "#EE9842", "#7649AE", "#5FA2DF",
          "#FBF652", "#60B94E", "#DF382D", "#7649AE", "#EE9842", "#DF382D",
          "#FBF652", "#5FA2DF", "#DF382D","#7649AE", "#60B94E")
y3 <- seq(from=(length(col3)-1)*.04,to=0, by=-.04)

ggplot() +
  geom_segment(aes(x = y3, xend=y3, y = 0,yend = 1.5 , color=rev(col3)), size=4.3) +
  theme_void() +
  theme(legend.position = "none") +
  coord_fixed(expand = T) +
  scale_color_identity() +
  ggsave("plot3.png", width=3)
```

```{r}
### combine all panels together
ggdraw() + 
  draw_image("plot1-cropped.png", scale = .45, x=.11 , y=-.3) +
  draw_image("plot2-cropped.png", scale = .95, x=-.3 , y=0) +
  draw_image("plot3-cropped.png", scale = .58, x=.11 , y=.186) +
  theme(plot.background = element_rect(fill="black", color = NA)) 

ggsave(filename="final.png", width=10, height=8, dpi=350)
```


